### ISSUE TITLE
Assignment 2 (BlueYelp) - Reviews

### ISSUE THREAD

**Issue by giaotuancse** [giaotuancse/Blue-Yelp#1]
Hi @coderschoolreview,
I just finished my assignment. Please review, thank you ;)

**Comment by coderschoolreview** [comment]
:+1: great work. The primary challenge of this homework was to learn how to use UITableView to manage a complex form, establish communication between view controllers, and apply the correct Auto Layout constraints. 

This was a challenging assignment, congrats on completing it successfully!

## Grading Summary:
- **Functionality**: Excellent
- **Code Style**: Needs Improvement
- **Visual Design**: Excellent
- **Usability**: Good
- **Overall**: Excellent

## Detailed Notes
- Good job specifying the Auto Layout constraints for business cell!
- Nice work linking the filter model with the controls. See this [popular form library](https://github.com/nicklockwood/FXForms) for an alternative to implementing forms manually.
- Nice work connecting the view controllers via the custom filter delegate. This is a popular pattern for handling events between view controllers.
- In `FilterViewController`, you can improve the UX when expanding or collapsing the section by using 

``` Swift
tableView.reloadSections(NSIndexSet(index: 0), withRowAnimation: .Automatic)
```
- Well done implementing detail page with map.
- Nice job customizing the switches.
- Please notice my comments in your code to improve your code style.

Excellent submission overall. Great job dedicating enough time to do the homework. You learned a lot! Keep up the good work :smile:

**Comment by chug2k** [comment]
**Significant** improvement from last week in terms of code style. Much better. You still have more room to improve, but thank you for listening to our comments and taking the time to clean up your code! :clap: :bow:
